#customer page
sc_admin_customer:
    pattern:  /
    defaults: { _controller: SmartCafeAdminBundle:Customer:view }
sc_admin_customer_get_list:
    pattern:  /get-list
    defaults: { _controller: SmartCafeAdminBundle:Customer:getList }
