#customer page
sc_admin_customer_hidden:
    pattern:  /
    defaults: { _controller: SmartCafeAdminBundle:Customer:view }
sc_admin_customer_hidden_get_list:
    pattern:  /get-list
    defaults: { _controller: SmartCafeAdminBundle:Customer:getList }
sc_admin_customer_hidden_save:
    pattern:  /save
    defaults: { _controller: SmartCafeAdminBundle:Customer:save }
sc_admin_customer_hidden_delete:
    pattern:  /delete
    defaults: { _controller: SmartCafeAdminBundle:Customer:delete }
