#admin home page
sc_admin_dashboard:
    resource: "@SmartCafeAdminBundle/Resources/config/routes/dashboard_routes.yml"
    prefix:   /
sc_admin_customer:
    path:   /customer.html
    defaults: { _controller: SmartCafeAdminBundle:Customer:view }
sc_admin_customer_hidden:
    resource: "@SmartCafeAdminBundle/Resources/config/routes/customer_routes.yml"
    prefix:   /customer
sc_admin_menu:
    resource: "@SmartCafeAdminBundle/Resources/config/routes/menu_routes.yml"
    prefix:   /menu
sc_admin_order:
    resource: "@SmartCafeAdminBundle/Resources/config/routes/order_routes.yml"
    prefix:   /order
