#admin home page
sc_admin_dashboard:
    resource: "@SmartCafeAdminBundle/Resources/config/routes/dashboard_routes.yml"
    prefix:   /
sc_admin_customer:
    path:   /customer.html
    defaults: { _controller: SmartCafeAdminBundle:Customer:view }
sc_admin_customer_hidden:
    resource: "@SmartCafeAdminBundle/Resources/config/routes/customer_routes.yml"
    prefix:   /customer
sc_admin_product:
    path:   /product.html
    defaults: { _controller: SmartCafeAdminBundle:Product:view }
sc_admin_product_hidden:
    resource: "@SmartCafeAdminBundle/Resources/config/routes/product_routes.yml"
    prefix:   /product
sc_admin_theme:
    path:   /theme.html
    defaults: { _controller: SmartCafeAdminBundle:Theme:view }
sc_admin_theme_hidden:
    resource: "@SmartCafeAdminBundle/Resources/config/routes/theme_routes.yml"
    prefix:   /theme
sc_admin_order:
    path:   /order.html
    defaults: { _controller: SmartCafeAdminBundle:Order:view }
sc_admin_order_hidden:
    resource: "@SmartCafeAdminBundle/Resources/config/routes/order_routes.yml"
    prefix:   /order
sc_admin_coffee_table_overview:
    path:   /coffee-table-overview.html
    defaults: { _controller: SmartCafeAdminBundle:CoffeeTableOverView:view }
sc_admin_coffee_table_overview_hidden:
    resource: "@SmartCafeAdminBundle/Resources/config/routes/coffee_table_overview_routes.yml"
    prefix:   /coffee-table-overview
